<div class="card">
	<div class="card-body">

		<h5 class="card-tittle">Hanock Rijkaard</h5>
		<h6 class="card-subtittle text-muted">Humano Paladino</h6>

	</div>
</div>

<div class="card">
	<div class="card-body">

		<h5 class="card-tittle">Hosven</h5>
		<h6 class="card-subtittle text-muted">Humano Guerreiro</h6>

	</div>
</div>

<a class="botao-flutuante" href="/criar_ficha">
	<i class="fas fa-plus-circle fa-5x text-primary"></i>
</a>