<div class="card mt-5">
	<div class="card-body">
		<form action="/autenticar" method="post">

			<h3 class="card-title">Entrar</h3>

			<div class="form-group">
				<input type="email" name="email" class="form-control" placeholder="Digite seu e-mail" required>
			</div>

			<div class="form-group">
				<input type="password" name="senha" class="form-control" placeholder="Digite sua senha" required>
			</div>

			<input type="submit" value="Entrar" class="btn btn-primary btn-block">
			
		</form>
	</div>
</div>