<section id="home" class="d-flex"><!-- Início da Seção de carousel -->
	<div class="container align-self-center"><!-- Início do Container -->

        <div class="carousel slide centralizar-texto" data-ride="carousel"><!-- Início do carousel slide -->
        	<div class="carousel-inner"><!-- Início do carousel inner -->

        		<div class="carousel-item active">
        			<a href="/fichas">
        				<h1>Fichas Online</h1>
        			</a>
                </div>

                <div class="carousel-item">
                	<a href="#">
                    	<h1>Grids Online</h1>
                 	</a>
                </div>

            </div><!-- /Fim do carousel inner -->
        </div><!-- /Fim do carousel slide -->

    </div><!-- /Fim do Container -->
</section><!-- /Fim da Seção -->
	